config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'
  get 'top' => 'posts#kebab_top'
  
  controller :sessions do
  	get 'login' => :new
  	post 'login' => :create
  	delete 'logout' => :destroy
  end

  resources :contacts
  resources :users
  resources :posts do
    resources :comments
    member do
      delete :delete_image
    end
  end
  root "posts#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
	has_ancestry
	belongs_to :post
	validates :name, presence: true, length: { minimum: 3 }
	validates :text, presence: true, length: { minimum: 5 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	protect_from_forgery except: :new

	def new
		@post = Post.find(params[:post_id])
		@comment = @post.comments.build
		@comment.parent_id = params[:parent_id]
		respond_to do |format|
			format.html
			format.js
		end
	end

	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(comment_params)
		respond_to do |format|
			if @comment.errors.any?
				@anchor = "comments_form"
				format.html { render 'posts/show' }
				format.js
			else
				format.html do
					flash[:success] = 'Comment posted.'
					redirect_to @post
				end
				format.js
			end
		end
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy
		respond_to do |format|
			format.html do
				flash[:success] = 'Comment deleted.'
				redirect_to post_path(@post)
			end
			format.js
		end
	end

	private

	def comment_params
      params.require(:comment).permit(:name, :text, :parent_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
	def nested_comments(comments)
		comments.map do |comment, sub_comments|
			render(comment) + content_tag(:div, nested_comments(sub_comments), :class => "nested_comments")
		end.join.html_safe
	end
end

app/views/comments/_comment.html.erb
<div class="card mb-3" id="comment-<%= comment.id %>">
		<% if comment.save %>
		<div class="card-header">
			<strong><%= comment.name %></strong> <span class="text-muted"><%= time_ago_in_words(comment.created_at.strftime("%F %H:%M")) %> ago</span>
		</div>
		<div class="card-body">
			<p class="card-text"><%= comment.text %></p>
		<% end %>
		<%= link_to 'Reply', new_post_comment_path(:post_id => @post.id, :parent_id => comment), format: :js, remote: true, class: "card-link" %>
		<% if session[:user_id] %>
			<%= link_to 'Delete', [comment.post, comment], method: :delete, remote: true, class: "delete" %>
		<% end %>
	</div>
</div>

app/views/comments/_form.html.erb
<button type="button" class="close">&times;</button>
<%= bootstrap_form_for ([@post, @post.comments.build]), remote: :true do |form| %>
  <% if @comment && @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= form.hidden_field :parent_id, :value => params[:parent_id] %>

  <%= form.text_field :name, id: :comment_name %>

  <%= form.text_area :text, id: :comment_text %>

  <%= form.submit %>
  
<% end %>

app/views/comments/create.js.erb
$('#comment-<%= @comment.parent_id %>').after('<%= j render @comment %>');
$('.new_comment').first().hide();
$('#comment_list').html('<%= j render @post %>');
$('.comment_form').html('<%= j render 'form' %>');

app/views/comments/destroy.js.erb
$('.delete').bind('ajax:success', function() {
	$('#comment-<%= @comment.id %>').fadeOut();
	$('#comment-<%= @comment.id %>').next('.nested_comments').fadeOut();
	$('#comment_list').html('<%= j render @post %>');
});

app/views/comments/new.html.erb
<div class="container">
  <div class = "row">
    <div class="col">
      <h3>Reply</h3>
	      <ol class ="comments">
	          <%= render @comment.parent if @comment.parent %>
	      </ol>
    </div>
	</div>
	<%= render 'form' %>
</div>

app/views/comments/new.js.erb
var $comment_form = $("<%= j render 'form', post: @post, comment: @comment %>");

$(document).ready(() => {
	$('.card-link').on('click', event => {
		$(event.currentTarget).closest('.card-body').append($comment_form);
	});
	$('.close').on('click', event => {
		$(event.currentTarget).next('.new_comment').hide();
		$(event.currentTarget).hide();
	});
});