config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'
  get 'top' => 'posts#kebab_top'
  
  controller :sessions do
  	get 'login' => :new
  	post 'login' => :create
  	delete 'logout' => :destroy
  end

  resources :contacts
  resources :users
  resources :posts do
    resources :comments
    member do
      delete :delete_image
    end
  end
  root "posts#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
	attr_accessor :delete_thumbnail
	after_save :purge_thumbnail, if: :delete_thumbnail
	has_many :comments, dependent: :destroy
	has_one_attached :thumbnail
	has_many_attached :images
	validates :title, :description, presence: true
	validates :title, length: { minimum: 5 }
	validates :description, length: { minimum: 10 }
	validate :image_exists

	def score
		score = (meat_taste + variety_of_salads + satiety + cleanliness + service) / 5.0
		"%g" % ("%.1f" % score)
	end

  private

  def image_exists
    errors.add(:base, 'Please upload your image.') unless thumbnail.attached?
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authorize, only: [:edit, :update, :destroy, :create, :new, :delete_image]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.sort{|a,b| b.score <=> a.score}
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_url, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def delete_image
    attachment = ActiveStorage::Attachment.find(params[:id])
    attachment.purge_later
    redirect_back(fallback_location: posts_path)
  end

  def kebab_top
    @posts = Post.all.sort{|a,b| b.score <=> a.score}
    @last_update = Post.order("updated_at").last.updated_at
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description, :thumbnail, :meat_taste, :variety_of_salads, :spiciness, :satiety, :cleanliness, :service, images: [])
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
 <%= bootstrap_form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.file_field :thumbnail %>

  <%= form.text_field :title, id: :post_title %>

  <%= form.file_field :images, multiple: true %>

  <%= form.text_area :description, id: :post_description %>

  <%= form.select(:meat_taste, options_for_select([1, 2, 3, 4, 5, 6, 7], :selected => @post.meat_taste )) %>

  <%= form.select(:variety_of_salads, options_for_select([1, 2, 3, 4, 5, 6, 7], :selected => @post.variety_of_salads )) %>

  <%= form.select(:spiciness, options_for_select([1, 2, 3, 4, 5, 6, 7], :selected => @post.spiciness )) %>

  <%= form.select(:satiety, options_for_select([1, 2, 3, 4, 5, 6, 7], :selected => @post.satiety )) %>

  <%= form.select(:cleanliness, options_for_select([1, 2, 3, 4, 5, 6, 7], :selected => @post.cleanliness )) %>

  <%= form.select(:service, options_for_select([1, 2, 3, 4, 5, 6, 7], :selected => @post.service )) %>

  <%= form.submit %>

<% end %>

app/views/posts/_post.html.erb
<h2><%= pluralize(@post.comments.count, 'Comment') %></h2>
<br>
<%= nested_comments @post.comments.arrange(:order => :created_at) %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>
<div class="container">
	<%= render 'form', post: @post %>
</div>
<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<head>
  <title>kblog</title>
</head>
<body>
  <div class="container">
      <div class="row">
        <% @posts.each do |post| %>
          <div class="col">
            <div class="card mx-auto" style="width: 500px">
                <img class="img-fluid card-img-top" <%= image_tag(post.thumbnail) %></img>
              <div class="card-body text-center">
                <h4 class="card-title"><%= post.title %></h4>
                <p class="card-text font-weight-bold text-danger">Score: <%= post.score %> / 7</p>
                <a href="<%= post_path(post) %>" class="btn btn-secondary">More info</a>
              </div>
            </div>
          </div>
        <% end %>
      </div>
  </div>
</body>

app/views/posts/kebab_top.html.erb
<div class="container">
</br>
	<h1 class="text-center">Kebab top overview</h1></br>
	<table class="table table-hover">
		<% @posts.each do |post| %>
		<thead class="thead-dark" data-toggle="collapse" data-target="#post-<%= post.id %>">
			<tr>
				<th><%= post.title %></th>
				<th><%= post.score %> / 7</th>
			</tr>
		</thead>
		<tbody id="post-<%= post.id %>" class="collapse font-weight-bold">
			<tr>
				<td>Meat taste: </td>
				<td><%= post.meat_taste %> / 7</td>
			</tr>
			<tr>
				<td>Variety of salads in kebab: </td>
				<td><%= post.variety_of_salads %> / 7</td>
			</tr>
			<tr>
				<td>Satiety feeling after eating: </td>
				<td><%= post.satiety %> / 7</td>
			</tr>
			<tr>
				<td>Kebab place cleanliness: </td>
				<td><%= post.cleanliness %> / 7</td>
			</tr>
			<tr>
				<td>Service rating: </td>
				<td><%= post.service %> / 7</td>
			</tr>
			<tr>
				<td>Kebab spiciness: </td>
				<td><%= post.spiciness %> / 7</td>
			</tr>
		</tbody>
		<% end %>
	</ol>
	</table>
	<p class="font-weight-bold text-danger">Last update: <%= @last_update.strftime("%F") %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<head>
  <title>kblog</title>
  <link href="https://fonts.googleapis.com/css?family=Mukta" rel="stylesheet">
  <% if @anchor %>
  	<script type="text/javascript">
  		window.location.hash = "<%= @anchor %>";
  	</script>
  <% end %>
</head>
<body>
	<h1 class="text-center"><%= @post.title %></h1></br>
	<div class="container">
    <div class="row">
    	<div class="col-6"><%= @post.description %></div>
    		<div class="col-6">
    			<div class="row">
						<% @post.images.each do |image| %>
							<div class="col-md-6 col-xs-6">
								<%= link_to image_tag(image), image, data: { lightbox: "image" } %>
								<% if session[:user_id] %>
									<%= link_to "Delete", delete_image_post_url(image.id), method: :delete %>
								<% end %>
							</div>
						<% end %>
					</div>
				</div>
		</div>


		<% if session[:user_id] %>
			<button type="button" class="btn btn-dark"><%= link_to 'Edit', edit_post_path(@post) %></button>
			<button type="button" class="btn btn-dark"><%= link_to 'Delete', @post, method: :delete %></button>
		<% end %>

		<button type="button" class="btn btn-dark"><%= link_to 'Back', posts_path %></button>
	</div>
	<br>
	<div class="container" id="comments">
		<div id="comment_list">
			<%= render 'post' %>
		</div>
		<div class="comment_form">
			<%= render 'comments/form' %>
		</div>
	</div>
</body>