config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'
  get 'top' => 'posts#kebab_top'
  
  controller :sessions do
  	get 'login' => :new
  	post 'login' => :create
  	delete 'logout' => :destroy
  end

  resources :contacts
  resources :users
  resources :posts do
    resources :comments
    member do
      delete :delete_image
    end
  end
  root "posts#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kblog</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <div class="jumbotron text-center" style="margin-bottom:0">
      <h1>Kebablog</h1>
      <p>background image coming soon</p> 
    </div>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark sticky-top">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="collapsibleNavbar">
      <ul class="navbar-nav" data-turbolinks="false">
          <li class="nav-item">
            <a class="nav-link active" href="<%= posts_path %>">Blog</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="<%= contacts_path %>">About us</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="<%= top_path %>">Kebab top</a>
          </li>
          <% if session[:user_id] %>
            <li class="nav-item">
              <a class="nav-link" href="<%= logout_path %>" data-method="delete">Logout</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= new_post_path %>">New Post</a>
            </li>
          <% end %>
      </ul>
    </nav>
    <%= yield %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>